'use strict'

// manejo de errores

try{
    
    x = 10;
    //miFuncion();
}
catch(error){
    console.log(error);
} 
finally{
    console.log('termina la ejecucion de errores');
}

console.log('continuamos...')